### ISSUE TITLE
Migration to version 13.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/sale-addons#137]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

# Modules to migrate

- [ ] sale_address_domain
- [ ] sale_analytic
- [ ] sale_crm_school
- [ ] sale_delivery_hour
- [ ] sale_line_pending_info
- [ ] sale_order_from_picking
- [ ] sale_order_line_copy
- [ ] sale_order_line_input_button
- [ ] sale_order_line_input_route
- [ ] sale_order_rental
- [ ] sale_order_template_print_section
- [ ] sale_order_weight_cost
- [ ] sale_partner_company
- [ ] sale_report_pivot_ext
- [ ] sale_school
- [ ] sale_school_generate_sepa
- [ ] sale_stock_analytic
- [ ] sale_template_price_update
- [ ] sales_team_analytic_tag

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
