### ISSUE TITLE
Migration to version 15.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/sale-addons#216]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-15.0

# Modules to migrate

- [ ] sale_address_domain
- [ ] sale_contact_partner
- [ ] sale_create_mandate
- [ ] sale_invoice_lines_history
- [ ] sale_line_pending_info
- [ ] sale_order_event_attendee
- [ ] sale_order_event_attendee_headquarter
- [ ] sale_order_headquarter
- [ ] sale_order_line_contract
- [ ] sale_order_line_contract_headquarter
- [ ] sale_order_line_cost
- [ ] sale_order_line_free_shipping
- [ ] sale_order_offer_version
- [ ] sale_order_type_config
- [ ] sale_order_usability
- [ ] sale_order_vehicle
- [ ] sale_project_usability
- [ ] website_sale_suggest_login

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list
