### ISSUE TITLE
Migration to version 12.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/sale-addons#31]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-12.0

# Modules to migrate

- [ ] sale_contract_specification
- [ ] sale_pricelist_limit
- [ ] sales_team_utilities
