### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by oihane** [avanzosc/sale-addons#7]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] sale_analytic_cost
- [ ] sale_crm_lead_link
- [ ] sale_delete_stock_warning
- [ ] sale_invoice_group
- [ ] sale_order_contract_increase_unit_price
- [ ] sale_order_copy_version
- [ ] sale_order_increase_unit_price
- [ ] sale_order_line_annual_price
- [ ] sale_order_line_attached_check
- [ ] sale_order_line_performance
- [ ] sale_order_line_service_view
- [ ] sale_order_purchase_split_info
- [ ] sale_order_renovate_contract
- [ ] sale_product_max_discount
- [ ] sale_service_recurrence_configurator
- [ ] sale_service_recurrence_configurator_product_variant
- [ ] sale_utilities
